### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by paulobreim** [srihariash999/animated_radio_buttons#1]
Please migrate you version to null safety urgent.

Thank You

**Comment by srihariash999** [comment]
Hi @paulobreim , Yes, I've been planning to, but haven't had time lately. Will do it soon.

**Comment by srihariash999** [comment]
Update your dependency to 1.0.0 , the package has been migrated to null safety with the PR #2 

Sorry for the inconvenience due to delay in maintaining package.

**Comment by paulobreim** [comment]
Thank you. Now I can release the new version of my program.
I am using your lib here:
https://play.google.com/store/apps/details?id=cbp.net.imoveiss

**Comment by paulobreim** [comment]
Thank you. Now I can release the new version of my program.
I am using your lib here:
"Raio X do Imóvel"
play.google.com/store/apps/details?id=cbp.net.imoveiss
